<?php

namespace QuadPBX\Components\Interfaces;

use QuadPBX\Quad;

abstract class BaseModuleDef
{
    protected Quad $quad;
    protected string $tenant;

    protected string $srcdir;

    /**
     * @param Quad   $quad   Core QuadPBX instance
     * @param string $srcdir Where this module is located on disk.
     *
     * @return void
     */
    public function __construct(Quad $quad, string $srcdir)
    {
        $this->quad = $quad;
        $this->tenant = $quad->getTenant();
        $this->srcdir = $srcdir;
    }

    /** @return string  */
    public function getSrcDir(): string
    {
        return $this->srcdir;
    }

    /**
     * Return an array of files that this module manages. May be empty.
     *
     * @return array
     */
    abstract public function filesManaged(): array;

    /**
     * Module should generate file and return what should be written to disk.
     *
     * @param string $filename From filesManaged()
     *
     * @return string
     */
    public function getProcessedFile(string $filename): string
    {
        throw new \Exception("Bug: Module needs to implement processFile for $filename");
    }

    /**
     * Return a single string identifying this module. For example,
     * the 'Extensions' module would return 'extensions'.
     *
     * @return string
     */
    abstract public function getModuleName(): string;

    /**
     * Generate a backup for this module. The output of this
     * should be able to be imported by 'restoreBackup'
     *
     * @return array
     */
    abstract public function getBackup(): array;

    /**
     * Import a backup created by 'getBackup'. Not sure
     * what it would return yet.
     *
     * @param array $backup Array generated by 'getBackup'
     *
     * @return array
     */
    abstract public function restoreBackup(array $backup): array;
}
